# Generated by Django 5.1.4 on 2025-03-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
